### ISSUE TITLE
Refactor: class components into functional components

### ISSUE THREAD

**Issue by kennethlee** [kennethlee/redux-todo#1]
Despite being stateless, some components were written as class components when they could/should have been written as stateless functional.

Rectify.

**Comment by thomasjinlo** [comment]
ButtonBar and the ItemList container do not require state but will connect(mapDispatchToProps) work on a pure functional component?

I think it is fine how we have it.
[Dan Abramov Presentational vs Container](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.jl3pfcvkx)

If you go to the presentational component section.

> Have no dependencies on the rest of the app, such as Flux actions or stores.

**Comment by kennethlee** [comment]
Yee. 4f08bc7
